### ISSUE TITLE
crate directory is missing a `Cargo.toml` file; is `native` the wrong directory? 

### ISSUE THREAD

**Issue by prashantjdgit** [enkra/enkra-send#10]

**Comment by prashantjdgit** [comment]
We are using this patch in flutter web app.
After installing the rust successfully ,we have to hit this command - ./build_tools/build_web.sh
but we are getting the error - Error: crate directory is missing a `Cargo.toml` file; is `native` the wrong directory?
Caused by: crate directory is missing a `Cargo.toml` file; is `native` the wrong directory?

Please guide.

**Comment by harryfei** [comment]
If you just use the flutter patch, you can skip building the rust stuff.
This project use rust just for some wasm api.

Besides, I don't know why you get the Cargo.toml error in your environment. What build_web.sh does is just using `wasm-pack` to build rust to wasm. It's a simple command, you can debug it.

**Comment by prashantjdgit** [comment]
Understood. We just want to build a flutter web app and apply the patch for performance improvements. Should we just run the patch script after flutter build web command?

**Comment by harryfei** [comment]
Yeah, you are right.

**Comment by prashantjdgit** [comment]
I am getting this error

./build_tools/patch_web.sh 
patch unexpectedly ends in middle of line
patch: **** Only garbage was found in the patch input.

**Comment by prashantjdgit** [comment]
I downloaded your code and copied build_tools and native folder into root of my flutter project, Did I missed something?

**Comment by harryfei** [comment]
Maybe flutter version, this patch needs flutter master channel.

You can view the patch files in build_tools and add changes to your generated `flutter.js` and `flutter_servicewoker.js`. It's easy to do it by manual.

**Comment by prashantjdgit** [comment]
I'm already on master channel btw

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.10.0-7.0.pre.16, on Ubuntu 22.04.2 LTS 5.19.0-41-generic, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] VS Code
[✓] Connected device (2 available)
[✓] Network resources
```

**Comment by harryfei** [comment]
Besides, flutter changes recently.

Replace those code in your patched flutter.js.
```
++      const isMobile = /Mobi/i.test(window.navigator.userAgent);
++      const isChromium = window.navigator.userAgent
++                               .toLowerCase()
++                               .indexOf('chrome') > -1;
++
++      if (!isMobile) {
++        if (isChromium) {
++          fetch("canvaskit/chromium/canvaskit.js");
++          fetch("canvaskit/chromium/canvaskit.wasm");
++        } else {
++          fetch("canvaskit/canvaskit.js");
++          fetch("canvaskit/canvaskit.wasm");
++        }
++      }
```

**Comment by prashantjdgit** [comment]
I was able to run it but at one place got error

.```
/build_tools/patch_web.sh 
patching file build/web/flutter.js
patch unexpectedly ends in middle of line
patching file build/web/flutter_service_worker.js
Hunk #1 succeeded at 90 with fuzz 1 (offset 61 lines).
Hunk #2 succeeded at 150 (offset 61 lines).
patch unexpectedly ends in middle of line
Hunk #3 succeeded at 180 with fuzz 1 (offset 61 lines).
```

**Comment by prashantjdgit** [comment]
Can you send us the new patch files?

**Comment by harryfei** [comment]
Sorry, it's not ready to share. You can check your patch result to verify it's patched correct or not.

It's know that flutter master channel changed flutter.js flutter_servicework.js frequently.

**Comment by prashantjdgit** [comment]
should I downgrade to specific master commit where I can apply your patch? Also when will you be able to share new patch?

**Comment by prashantjdgit** [comment]
> Besides, flutter changes recently.
> 
> Replace those code in your patched flutter.js.
> 
> ```
> ++      const isMobile = /Mobi/i.test(window.navigator.userAgent);
> ++      const isChromium = window.navigator.userAgent
> ++                               .toLowerCase()
> ++                               .indexOf('chrome') > -1;
> ++
> ++      if (!isMobile) {
> ++        if (isChromium) {
> ++          fetch("canvaskit/chromium/canvaskit.js");
> ++          fetch("canvaskit/chromium/canvaskit.wasm");
> ++        } else {
> ++          fetch("canvaskit/canvaskit.js");
> ++          fetch("canvaskit/canvaskit.wasm");
> ++        }
> ++      }
> ```

Do I need to update your patch file with this code?

**Comment by harryfei** [comment]
> should I downgrade to specific master commit where I can apply your patch? Also when will you be able to share new patch?

try to downgrade flutter to a commit at March 1. I think they don't change at that time.

**Comment by prashantjdgit** [comment]
I have tried to update flutter.js.patch  but getting below error
```
patching file build/web/flutter.js
patch: **** malformed patch at line 21: +        } 
```

```
--- build/web/flutter.js.orig	2023-03-01 15:40:58.588065610 +0800
+++ build/web/flutter.js	2023-03-01 15:43:48.879605009 +0800
@@ -375,7 +375,16 @@
       // Install the `didCreateEngineInitializer` listener where Flutter web expects it to be.
       this.didCreateEngineInitializer =
         entrypointLoader.didCreateEngineInitializer.bind(entrypointLoader);
-      return entrypointLoader.loadEntrypoint(entrypoint);
+      const main = entrypointLoader.loadEntrypoint(entrypoint);
+      const isMobile = /Mobi/i.test(window.navigator.userAgent);
+      const isChromium = window.navigator.userAgent
+                               .toLowerCase()
+                               .indexOf('chrome') > -1;
+
+      if (!isMobile) {
+        if (isChromium) {
+          fetch("canvaskit/chromium/canvaskit.js");
+          fetch("canvaskit/chromium/canvaskit.wasm");
+        } else {
+          fetch("canvaskit/canvaskit.js");
+          fetch("canvaskit/canvaskit.wasm");
+        }
+      }
+      fetch("assets/FontManifest.json");
+      fetch("assets/fonts/MaterialIcons-Regular.otf");
+      fetch("assets/packages/cupertino_icons/assets/CupertinoIcons.ttf");
+      fetch("/");
+
+      return main;
     }
   }
 
```

**Comment by prashantjdgit** [comment]
I found this flutter commit release tag - https://github.com/flutter/flutter/releases/tag/3.7.6 .
What is proper way to downgrade flutter to this? 
I went into installed flutter SDK folder and checked out this tag by using git checkout 3.7.6
But after this flutter doctor shows channel unknown instead of master. Is this correct?

**Comment by harryfei** [comment]
I have no experience about downgrading the flutter.

**Comment by harryfei** [comment]
@prashantjdgit I add the new patch in master branch. The patch don't need flutter nightly anymore.

**Comment by Sucio505** [comment]
Theodore Manzanares
