### ISSUE TITLE
speed up flutter web loading speed

### ISSUE THREAD

**Issue by Rest00rer** [enkra/enkra-send#9]
hello, please tell me why the serviceworker does not load canvaskit.wasm and more?
![image](https://user-images.githubusercontent.com/100043389/233771453-e2b720b7-67e0-483f-b89c-abf5ff71c025.png)
![image](https://user-images.githubusercontent.com/100043389/233771521-00a007c4-863d-4223-9208-82d4ca9e626f.png)

**Comment by harryfei** [comment]
https://github.com/enkra/enkra-send/blob/db0dcacc2048ba0454e3ee7f6e26756c761d850c/web/index.html#L87-L89

Do you use  the self-hosted `canvaskit.wasm`?  serviceworker doesn't cache the cdn  based canvaskit.wasm.
